### ISSUE TITLE
This is an absolute ass to compile. Would be awesome if it could already be packaged as .exe or w/e.

### ISSUE THREAD

**Issue by Dave3848** [AgentMC/KbLayoutUnloader#1]
Like. I'm telling you. Fr.

**Comment by Dave3848** [comment]
Also not everyone has Visual Studio. I tried to compile it through Replit. That went to shitsticks.

**Comment by AgentMC** [comment]
VS Community is free, come on. But ok, will do when my fever goes away :(

Надіслано з Outlook для Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AgentMC** [comment]
@Dave3848  there is a compiled version since 2023: https://github.com/AgentMC/KbLayoutUnloader/releases/tag/v.1.0.0 The zip has the exe and pdb inside... It requires the VC Runtime 14.0 (2022), you can install it from here https://aka.ms/vs/17/release/vc_redist.x86.exe Let me know if any issues.

**Comment by Dave3848** [comment]
> @Dave3848 there is a compiled version since 2023: https://github.com/AgentMC/KbLayoutUnloader/releases/tag/v.1.0.0 The zip has the exe and pdb inside... It requires the VC Runtime 14.0 (2022), you can install it from here https://aka.ms/vs/17/release/vc_redist.x86.exe Let me know if any issues.

Damn. Sorry for not noticing this earlier. I stand corrected. Thank you for the .exe and for pointing it out! Slava Ukraini.
